# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
# Version 0.0.1
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import pandas as pd
import dateutil.parser

# Save file name here
name = 'test'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 10, 881, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 877, 177))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")

        # Import CSV
        self.input_table = pd.read_csv(f'data/{name}.csv')
        self.display_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.display_table.setGeometry(QtCore.QRect(0, 0, 881, 181))
        self.display_table.setObjectName("display_table")

        self.view_table()

        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_table.setHorizontalHeaderItem(6, item)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.addEntryButton = QtWidgets.QPushButton(self.centralwidget)
        self.addEntryButton.setGeometry(QtCore.QRect(820, 290, 81, 26))
        self.addEntryButton.setObjectName("addEntryButton")
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setGeometry(QtCore.QRect(20, 200, 31, 16))
        self.date_label.setObjectName("date_label")
        self.miles_label = QtWidgets.QLabel(self.centralwidget)
        self.miles_label.setGeometry(QtCore.QRect(100, 200, 60, 16))
        self.miles_label.setObjectName("miles_label")
        self.cat_label = QtWidgets.QLabel(self.centralwidget)
        self.cat_label.setGeometry(QtCore.QRect(190, 200, 60, 16))
        self.cat_label.setObjectName("cat_label")
        self.part_label = QtWidgets.QLabel(self.centralwidget)
        self.part_label.setGeometry(QtCore.QRect(300, 200, 31, 16))
        self.part_label.setObjectName("part_label")
        self.product_label = QtWidgets.QLabel(self.centralwidget)
        self.product_label.setGeometry(QtCore.QRect(430, 200, 60, 16))
        self.product_label.setObjectName("product_label")
        self.cost_label = QtWidgets.QLabel(self.centralwidget)
        self.cost_label.setGeometry(QtCore.QRect(540, 200, 60, 16))
        self.cost_label.setObjectName("cost_label")
        self.notes_label = QtWidgets.QLabel(self.centralwidget)
        self.notes_label.setGeometry(QtCore.QRect(610, 200, 60, 16))
        self.notes_label.setObjectName("notes_label")
        self.date_box = QtWidgets.QDateEdit(self.centralwidget)
        self.date_box.setGeometry(QtCore.QRect(20, 220, 71, 31))
        self.date_box.setObjectName("date_box")
        self.miles_box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.miles_box.setGeometry(QtCore.QRect(100, 220, 81, 31))
        self.miles_box.setObjectName("miles_box")
        self.cat_drop = QtWidgets.QComboBox(self.centralwidget)
        self.cat_drop.setGeometry(QtCore.QRect(190, 221, 101, 31))
        self.cat_drop.setObjectName("cat_drop")
        self.cat_drop.addItem("")
        self.cat_drop.addItem("")
        self.cat_drop.addItem("")
        self.cat_drop.addItem("")
        self.part_drop = QtWidgets.QComboBox(self.centralwidget)
        self.part_drop.setGeometry(QtCore.QRect(300, 220, 121, 31))
        self.part_drop.setObjectName("part_drop")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.part_drop.addItem("")
        self.product_box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.product_box.setGeometry(QtCore.QRect(430, 220, 104, 31))
        self.product_box.setObjectName("product_box")
        self.cost_box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cost_box.setGeometry(QtCore.QRect(540, 220, 61, 31))
        self.cost_box.setPlainText("")
        self.cost_box.setObjectName("cost_box")
        self.notes_box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.notes_box.setGeometry(QtCore.QRect(610, 220, 291, 64))
        self.notes_box.setObjectName("notes_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Update name.csv and save
        self.actionSave.triggered.connect(lambda: self.save_csv())

        # Add record
        self.addEntryButton.clicked.connect(lambda: self.add_entry([
            str(dateutil.parser.parse(self.date_box.date().toString()).date().strftime('%-m/%-d/%y')),
            self.miles_box.toPlainText(), self.cat_drop.currentText(), self.part_drop.currentText(),
            self.product_box.toPlainText(), self.cost_box.toPlainText(), self.notes_box.toPlainText()
        ]))

    def view_table(self):
        # Specify table dimensions
        n_rows = len(self.input_table.index)
        n_cols = len(self.input_table.columns)
        self.display_table.setColumnCount(n_cols)
        self.display_table.setRowCount(n_rows)
        # Load data
        for i in range(n_rows):
            for j in range(n_cols):
                self.display_table.setItem(i, j, QTableWidgetItem(str(self.input_table.iat[i, j])))
        # Update dimensions
        self.display_table.resizeColumnsToContents()
        self.display_table.resizeRowsToContents()

    def add_entry(self, values):
        self.input_table.loc[len(self.input_table)] = values
        self.view_table()

    def save_csv(self):
        self.input_table.to_csv(f'data/{name}.csv')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.display_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.display_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Miles"))
        item = self.display_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category"))
        item = self.display_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Part"))
        item = self.display_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Product"))
        item = self.display_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Cost"))
        item = self.display_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Notes"))
        self.addEntryButton.setText(_translate("MainWindow", "Add Entry"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.miles_label.setText(_translate("MainWindow", "Miles"))
        self.cat_label.setText(_translate("MainWindow", "Category"))
        self.part_label.setText(_translate("MainWindow", "Part"))
        self.product_label.setText(_translate("MainWindow", "Product"))
        self.cost_label.setText(_translate("MainWindow", "Cost"))
        self.notes_label.setText(_translate("MainWindow", "Notes"))
        self.cat_drop.setItemText(0, _translate("MainWindow", "Maintenance"))
        self.cat_drop.setItemText(1, _translate("MainWindow", "Add-on"))
        self.cat_drop.setItemText(2, _translate("MainWindow", "Mod"))
        self.cat_drop.setItemText(3, _translate("MainWindow", "Inspection"))
        self.part_drop.setItemText(0, _translate("MainWindow", "Oil"))
        self.part_drop.setItemText(1, _translate("MainWindow", "Oil filter"))
        self.part_drop.setItemText(2, _translate("MainWindow", "Engine air filter"))
        self.part_drop.setItemText(3, _translate("MainWindow", "Cabin air filter"))
        self.part_drop.setItemText(4, _translate("MainWindow", "Tires"))
        self.part_drop.setItemText(5, _translate("MainWindow", "Wheels"))
        self.part_drop.setItemText(6, _translate("MainWindow", "Belts"))
        self.part_drop.setItemText(7, _translate("MainWindow", "Fuel filter"))
        self.part_drop.setItemText(8, _translate("MainWindow", "Transmission"))
        self.part_drop.setItemText(9, _translate("MainWindow", "Alternator"))
        self.part_drop.setItemText(10, _translate("MainWindow", "Pulleys"))
        self.part_drop.setItemText(11, _translate("MainWindow", "Exhaust"))
        self.part_drop.setItemText(12, _translate("MainWindow", "Wiring"))
        self.part_drop.setItemText(13, _translate("MainWindow", "Fuses"))
        self.part_drop.setItemText(14, _translate("MainWindow", "Accessories"))
        self.part_drop.setItemText(15, _translate("MainWindow", "Interior"))
        self.part_drop.setItemText(16, _translate("MainWindow", "Lights"))
        self.part_drop.setItemText(17, _translate("MainWindow", "Wipers"))
        self.part_drop.setItemText(18, _translate("MainWindow", "Body"))
        self.part_drop.setItemText(19, _translate("MainWindow", "Frame"))
        self.part_drop.setItemText(20, _translate("MainWindow", "Brakes"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
